sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
- npm run test
after_success: npm run coveralls
env:
  SNYK_TOKEN:
    secure: mzoc9Mc1B0T8/NkASDchYfd/9Vs/iwmzdYYgtiF44YKdwiBykM8hDSKeN48EjwZ9xys7DCyQ8U/uiecufTqmqKEyXDwqpyesrNWnkHvzapW4JWetMvE2tbJ83InktvUTilnvgCqJc+lEclGM8PmiuhgCY8RCJ34uuY/51Ry38/IVRF70Fes3fw+bydLLHKbH3xAygp2cQ4h6iei+sBlWrWcYHoZLA5VeBh+56gg2Rr+AqMV7u+1regPXCa02qPHLEjEiVqyHeYGgbb3eNcjmWcmIO9ZUQ6Ivl6k6bxrlsGs1by8aObGRfrrPXcKw3LKzQEbkDaK3vfS8VlPV+q8u9OpEVmPYNVr5PYJ2EKjcMAr3pYFGAsnPrPyrb3R4wMAdm8e8gEsi6HwYAOh8keYRzzvtafV+221aBBnirrARBXJf9jRw/wnX1qtGPl1EE0aB8pIpxJ60CKDxmREvajfeh5TakYae+MUK4tMK+o597SbJVlv8agBHUiDcMrIUEMkkqNdegttJ8RrmFb/gpVyc+Sf2Ipa+TCYf4vkhbO+1Iym+aZV9k/7jS/ddPZ8crQYiRz4h5rtqlOnfP8WsTx6jLJNZZ+lgFkGBBu8PJQcYwQLPyZChv1/7aImLAGLz/SQfoHt3aTgo1/jUQFs85bWTHz+7psz8N840CJOAfS9dRRo=
before_deploy:
- npm run build
deploy:
  provider: npm
  email: adonisv79@gmail.com
  skip_cleanup: true
  api_key:
    secure: lUpxMi8XfEwhBySD6eVlaYVZyCNoHaq7c+GPkeR2IAxHuASRiCUYY+1kBK/mhICkZq3QsfDvFHImFMHanKvEE8KJIPdRFye9/D8S4tQm/76c61o+aCBIZDXLeenU0q0dYXS7vX6yVUgdjRIvAqql0RbqYDz2chWHQDe3gct6tTrTPFmgZDh/jrXmHt4mv5wPVFD/7oj4kF4FLfzapppyUwfBxio6VUDMoHdV1YgAA4v7NpFxJlEPLVdRcn1z8ggD8G58rnpA1S1XpEd7JyeHurYQAPiElt/BGkwqsYKV1uQbqi31huWQoOmeCLKam3D5vCie0Mj0tuCUbKWsfZKvH/dXr64qaAp59f7XUpoq7+vKNgrFzUZ+dFCbzBCdIug0QWWFZIki2pmV3/g6EKZ0lo8dsOUGg6GUx1e3KvYvuGKvafRQ0br6lKDbVxGJrithmqHtVGfNMpWpSJIHYoyqXbGnEKNv+oB2JsH1AXfMrC2Su5u2uZ1afL0JL3vTq+qaVqyragi2SAw3T8WNXYU0yIS6tHQDPK66nCpgVBeD5tmWuL0AsB+P1YKGVXbqDoY2DdpSwVmceOMvRExvNTjnPHbtWcxhFnSwpIDbGFKFTJCAlyMF2KQdggybj7kph3WGUhPdXAmNwka+bFN01zlT17dbl9LFBIcJH44RDrHCoQk=
  on:
    tags: true
    branch: master
